- name: 'Delete Folder from Azure'
  hosts: 
    - localhost

  tasks:
  - name: Remove folder
    ansible.windows.win_powershell:
      chdir : C:\
      script: |
        az storage fs directory delete --file-system {{container_name}}} --name {{Directory_Name}} --account-key {{key}} --account-name {{accont_name}}