# use files parameter to use multiple docker-compose.yml files
- name: Docker Compose Container
  hosts: 
    - testides.indicomain.local
  tasks:
  #Portal-Internal
  - name: Download ":latest" Portal-Internal
    win_shell: docker pull indicobuilds/portal-internal-dev:latest
    
  - name: Stop current Portal-Internal
    win_shell: docker container stop portal-internal
    ignore_errors: true #ignore if container is not running
      
  - name: Compose new Portal-Internal
    win_shell: cd C:\Docker\All | docker-compose -f docker-compose.portal.internal.yml --env-file=portal.internal.env up -d

  - name: New Container Composed
    win_shell: docker ps -f "name=portal-internal" -f status=running -f health=starting
    register: result
    
  - assert:
        that:
          - "'portal-internal' in result.stdout"


