# use files parameter to use multiple docker-compose.yml files
- name: Docker Compose Container
  hosts: 
    - testides.indicomain.local
  tasks:
  #Publishing-Service
  - name: Download ":latest" Publishing-Service
    win_shell: docker pull indicobuilds/publishing-service-dev:latest
        
  - name: Stop current Publishing-Service
    win_shell: docker container stop publishing-service
    ignore_errors: true #ignore if container is not running
    
  - name: Compose new Publishing-Service
    win_shell: cd C:\Docker\All | docker-compose -f docker-compose.publishing.service.yml --env-file=publishing.service.env up -d

  - name: New Container Composed
    win_shell: docker ps -f "name=publishing-service" -f status=running -f health=starting
    register: result
    
  - assert:
        that:
          - "'publishing-service' in result.stdout"


