# use files parameter to use multiple docker-compose.yml files
- name: Docker Compose Container
  hosts: 
    - testides3.indicomain.local
  tasks:
  #Portal-External
  - name: Download ":latest" Portal-External
    win_shell: docker pull indicobuilds/portal-external-dev:latest
    
  - name: Stop current Portal-External
    win_shell: docker container stop portal-external
    ignore_errors: true #ignore if container is not running
      
  - name: Compose new Portal-External
    win_shell: cd C:\Docker\All | docker-compose -f docker-compose.portal.external.yml --env-file=portal.external.env up -d

  - name: New Container Composed
    win_shell: docker ps -f "name=portal-external" -f status=running -f health=starting
    register: result
    
  - assert:
        that:
          - "'portal-external' in result.stdout"


