# use files parameter to use multiple docker-compose.yml files
- name: Docker Compose Container
  hosts: 
    - testides.indicomain.local
    - testides3.indicomain.local
  tasks:
  #Helper-Services
  - name: Download ":latest" Helper-Services
    win_shell: docker pull indicobuilds/helper-services-dev:latest
        
  - name: Stop current Helper-Services
    win_shell: docker container stop helper-services 
    ignore_errors: true #ignore if container is not running
    
  - name: Compose new Helper-services
    win_shell: cd C:\Docker\All | docker-compose -f docker-compose.helper.services.yml --env-file=helper.services.env up -d

  - name: New Container Composed
    win_shell: docker ps -f "name=helper-services" -f status=running -f health=starting
    register: result
    
  - assert:
        that:
          - "'helper-services' in result.stdout"


